#!/bin/bash

HERE=`pwd`
HOST=`hostname`
BACKUPDIR=${HOME}/.dotfiles.bk__`date +%F_\%T | sed s/:/-/g`

# backups a given file with a link to the new one
backup() {
    # Force create/backup the symlink.
    TARGET=${HOME}/${2}
    LINK=${HERE}/${1}
    if [ -f $TARGET ]
    then
        cp -arH $TARGET ${BACKUPDIR}
        rm -rf $TARGET
    fi
    ln -fs $LINK $TARGET
}

replace() {
    # Force create/backup the symlink.
    TARGET=${HOME}/${2}
    LINK=${HERE}/${1}
    [[ -e "$TARGET" ]]  && rm -rf $TARGET
    ln -fs $LINK $TARGET
}

# a safe makedir
makedir() {
    if [ ! -d ${HOME}/${1} ]
    then
        mkdir -p ${HOME}/${1}
    fi
}

mirrorfiles() {
    mkdir -p ${BACKUPDIR}
    
    backup "bash/bashrc"            ".bashrc"
    backup "tmux/tmux.conf"         ".tmux.conf"
    backup "tmux/tmux"              ".tmux"
    backup "git/gitconfig"          ".gitconfig"
    backup "git/gitignore"          ".gitignore"
    backup "vim/vimrc"              ".vimrc"
    backup "vim/vim"                ".vim"
    backup "zsh/oh-my-zsh"          ".oh-my-zsh"
    backup "zsh/zshrc"              ".zshrc"

    case $HOST in
        serenity)
            backup "bash/bashrc.serenity"      ".bashrc.local"
            backup "zsh/zshrc.serenity"        ".zshrc.local"
            ;;
        dain)
            backup "bash/bashrc.ccmr"          ".bashrc.local"
            ;;
        ept)
            backup "bash/bashrc.ccmr"          ".bashrc.local"
            ;;
        kempt)
            backup "bash/bashrc.ccmr"          ".bashrc.local"
            ;;
        *)
            touch ${HERE}/bash/bashrc.$HOST
            touch ${HERE}/zsh/zshrc.$HOST
            backup "bash/bashrc.$HOST"         ".bashrc.local"
            backup "zsh/zshrc.$HOST"           ".zshrc.local"
            ;;
    esac
}


# Verify that the user wants to proceed before potentially overwriting files
echo "Warning: This may overwrite your existing dotfiles."
read -p "Continue? (y/n) " -n 1
echo

if [[ $REPLY =~ ^[Yy]$ ]] ; then
    mirrorfiles
    source ${HOME}/.bashrc
else
    echo "Aborting..."
    exit 1
fi
